apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sem-share-pvc
spec:
  storageClassName: ""
  volumeName: sem-share-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sem-tomcat-pvc
spec:
  storageClassName: ""
  volumeName: sem-tomcat-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sem-jvmsecurity-pvc
spec:
  storageClassName: ""
  volumeName: sem-jvmsecurity-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sem-fonts-pvc
spec:
  storageClassName: ""
  volumeName: sem-fonts-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sem-logsdir-pvc
spec:
  storageClassName: ""
  volumeName: sem-logsdir-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
