apiVersion: v1
kind: Service
metadata:
  name: semerp-COMPANY_TAG
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30080
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30443
      name: https
    - port: 8009
      targetPort: 8009
      nodePort: 30009
      name: ajp
  selector:
    run: semerp-COMPANY_TAG