apiVersion: v1
kind: PersistentVolume
metadata:
  name: sem-share-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: SEM_SETUP_DIR/anamar-upload
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sem-tomcat-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: SEM_SETUP_DIR/conf
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sem-jvmsecurity-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: SEM_SETUP_DIR/jvmSecurity
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sem-fonts-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: SEM_SETUP_DIR/fonts
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sem-logsdir-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: SEM_SETUP_DIR/logs

