apiVersion: v1
kind: Service
metadata:
  name: sem-office-server
spec:
  selector:
    app: sem-office-server
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  type: NodePort
