heartbeat.monitors:
- type: http
  schedule: '@every 10m'
  urls:
    - http://semerp-uzmar.uzmar.svc.cluster.local:8090/sem
  data_stream:
    dataset: "heartbeat"
    namespace: "uzmar"
  id: semerp-uzmar
  name: SEMERP (UZMAR)
- type: http
  schedule: '@every 10m'
  urls:
    - http://analytics.uzmar.com:5040
  data_stream:
    dataset: "heartbeat"
    namespace: "uzmar"
  id: nlm-uzmar
  name: NLM (UZMAR)
- type: tcp
  schedule: '@every 10m'
  hosts: ["192.168.34.67"]
  ports: [1433]
  data_stream:
    dataset: "heartbeat"
    namespace: "uzmar"
  id: mssql-uzmar
  name: MSSQL (UZMAR)
- type: tcp
  schedule: '@every 10m'
  hosts: ["192.168.34.4"]
  ports: [5672]
  data_stream:
    dataset: "heartbeat"
    namespace: "uzmar"
  id: rabbitmq-uzmar
  name: RabbitMQ (UZMAR)
processors:
  - add_observer_metadata:
    cache.ttl: 10m
    geo:
      name: uzmar
      location: 40.7209248, 29.8659619
      continent_name: Asia
      country_iso_code: TR
      region_name: Turkey
      region_iso_code: K
      city_name: Kocaeli
output.elasticsearch:
  hosts: ['http://elastic.semerp.com:9202']
  username: elastic
  password: sem2023.*
http.enabled: true
http.host: 0.0.0.0
setup.kibana:
  host: http://kibana.semerp.com:5601
  username: elastic
  password: sem2023.*
