apiVersion: v1
kind: Service
metadata:
   name: document-converter
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30081
    targetPort: 8080
    name: http
  selector:
    run: document-converter
