## Metricbeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/metricbeat.docker.yml
#


#-------------------------------- Autodiscovery -------------------------------
# Autodiscover allows you to detect changes in the system and spawn new modules as they happen.
metricbeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
      hints.enabled: true

metricbeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  metricsets: ["cpu", "load", "memory"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 5m
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 5m
  metricsets:
    - filesystem
    - fsstat
  processors:
    - drop_event.when.regexp:
        system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 5m
  metricsets:
    - uptime

##------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "healthcheck", "info", "memory"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 5m

#================================ Processors ===================================
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale:
      format: offset
  - add_host_metadata:
      netinfo.enabled: true


#metricbeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    # Reload module configs as they change:
#    reload.enabled: false
#
#metricbeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true
#
#metricbeat.modules:
#- module: docker
#  metricsets:
#    - container
#    - cpu
#    - diskio
#    - healthcheck
#    - info
#    #- image
#    - memory
#    - network
#  hosts: ['unix:///var/run/docker.sock']
#  period: 10s
#  enabled: true
#
#processors:
#  - add_cloud_metadata: ~

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: elastic
  password: ${ELASTIC_PASSWORD}
  ssl:
    certificate_authorities: ['${path.home}/elasticsearch-ca.pem']

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/metricbeat/current/http-endpoint.html
#

http.enabled: true
http.host: 0.0.0.0

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true


#============================== Kibana =========================================
setup.kibana:
  host: ${KIBANA_HOST}
#  protocol: "https"
#  ssl.enabled: true
  username: ${KIBANA_SYSTEM_USERNAME}
  password: ${KIBANA_SYSTEM_PASSWORD}