apiVersion: v1
kind: PersistentVolume
metadata:
  name: nlm-conf-pv
spec:
  capacity:
    storage: 1Mi
  storageClassName: nlmconf
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: NLM_PATH/conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nlm-conf-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nlmconf
  resources:
    requests:
      storage: 1Mi
